namespace Meepl.Util;

public class SQLCommands
{
    public const string CREATE_TABLEBOUND_PROFILE = "CREATE TABLE IF NOT EXISTS TABLEBOUND_PROFILE (TABLEBOUNDID BIGINT PRIMARY KEY FOREGIN KEY, USERNAME VARCHAR(16), BIO VARCHAR(200), ICONCDNLINK VARCHAR(128), ACTION varchar(32), TITLE BIGINT, STATUS SMALLINT);";

    #region Platform Identifiers

    public const string CREATE_PASSKEYS = "CREATE TABLE IF NOT EXISTS PASSKEYS (CREDENTIAL_ID BYTEA, CREDENTIAL_PUBLIC_KEY BYTEA, TABLEBOUNDID BIGINT, SIGNINCOUNTER INT, CREDENTIAL_ID_LENGTH INT, CREDENTIAL_PUBLIC_KEY_LENGTH INT, CREATIONTIME TIMESTAMPTZ, LASTUPDATED TIMESTAMPTZ, LASTUSED TIMESTAMPTZ, CONSTRAINT FK_TID FOREIGN KEY (TABLEBOUNDID) REFERENCES TABLEBOUND_PROFILE (TABLEBOUNDID));";
    public const string CREATE_STEAM_PROFILE = "CREATE TABLE IF NOT EXISTS STEAM_PROFILE (TABLEBOUNDID BIGINT, STEAMID BIGINT PRIMARY KEY, CONSTRAINT FK_TID FOREIGN KEY (TABLEBOUNDID) REFERENCES TABLEBOUND_PROFILE(TABLEBOUNDID));";
    public const string CREATE_APPLE_PROFILE = "CREATE TABLE IF NOT EXISTS APPLE_PROFILE (TABLEBOUNDID BIGINT, APPLEID BIGINT PRIMARY KEY, CONSTRAINT FK_TID FOREIGN KEY (TABLEBOUNDID) REFERENCES TABLEBOUND_PROFILE(TABLEBOUNDID));";
    public const string CREATE_META_PROFILE = "CREATE TABLE IF NOT EXISTS META_PROFILE (TABLEBOUNDID BIGINT, METAID BIGINT PRIMARY KEY, CONSTRAINT FK_TID FOREIGN KEY (TABLEBOUNDID) REFERENCES TABLEBOUND_PROFILE(TABLEBOUNDID));";
    public const string CREATE_EPIC_PROFILE = "CREATE TABLE IF NOT EXISTS EPIC_PROFILE (TABLEBOUNDID BIGINT, EPICID BIGINT PRIMARY KEY, CONSTRAINT FK_TID FOREIGN KEY (TABLEBOUNDID) REFERENCES TABLEBOUND_PROFILE(TABLEBOUNDID));";
    public const string CREATE_DISCORD_PROFILE = "CREATE TABLE IF NOT EXISTS DISCORD_PROFILE (TABLEBOUNDID BIGINT, DISCORDID BIGINT PRIMARY KEY, CONSTRAINT FK_TID FOREIGN KEY (TABLEBOUNDID) REFERENCES TABLEBOUND_PROFILE(TABLEBOUNDID));";
    public const string CREATE_BLACKLISTED_USERNAMES = "CREATE TABLE IF NOT EXISTS BLACKLISTED_USERNAMES (USERNAME VARCHAR(16));";

    #endregion
    
    public const string CREATE_PROFILE_BADGES_TABLE = "CREATE TABLE IF NOT EXISTS PROFILE_BADGES (TABLEBOUNDID BIGINT PRIMARY KEY FOREGIN KEY, BADGECONTAINERBLOB BYTEA, VISABLEBADGECONTAINERBLOB BYTEA);";
    public const string CREATE_SESSIONS_TABLE = "CREATE TABLE IF NOT EXISTS SESSIONS_TABLE (TABLEBOUNDID BIGINT PRIMARY KEY FOREGIN KEY, IP VARCHAR(40), LOGIN TIMESTAMPZ, LOGOUT TIMESTAMPZ, DURATION INT, DEVICE VARCHAR(128), EXPERIENCEIDENTIFIER INT FOREGIN KEY);";
    public const string CREATE_FRIEND_REQUESTS_TABLE = "CREATE TABLE IF NOT EXISTS FRIEND_REQUESTS (ISSUER BIGINT FOREGIN KEY, REQUESTIE BIGINT FOREGIN KEY, MSG VARCHAR(128), ORIGIN BTYE, EXPERIENCEIDENTIFIER INT FOREGIN KEY);";
    public const string CREATE_EXPERIENCES_TABLE = "CREATE TABLE IF NOT EXISTS EXPERIENCES_TABLE (EXPERIENCEIDENTIFIER INT PRIMARY KEY, EXPERIENCEBLOB BYTEA, BLOBHASH STRING);";
    public const string CREATE_BLOCKED_TABLE = "CREATE TABLE IF NOT EXISTS PROFILE_BADGES (TABLEBOUNDID BIGINT PRIMARY KEY FOREGIN KEY, BADGECONTAINERBLOB BYTEA, VISABLEBADGECONTAINERBLOB BYTEA);";
    public const string CREATE_FRIENDS_TABLE = "CREATE TABLE IF NOT EXISTS FRIENDS_TABLE (TABLEBOUNDID BIGINT PRIMARY KEY FOREGIN KEY, FRIENDBLOB BYTEA, CONTAINERHASH STRING);";
public const string CREATE_CLANS_TABLE = "CREATE TABLE IF NOT EXISTS CLANS_TABLE (CLANID BIGINT PRIMARY KEY, CLANBLOB BYTEA, BLOBHASH STRING);";
    public const string CREATE_BADGES_TABLE = "CREATE TABLE IF NOT EXISTS BADGES_TABLE (BADGEID BIGINT PRIMARY KEY, BADGEBLOB BYTEA, BADGEHASH VARCHAR(128));";
    public const string CREATE_EVENTS_TABLE = "CREATE TABLE IF NOT EXISTS EVENTS_TABLE (EVENTID BIGINT PRIMARY KEY, EVENTBLOB BYTEA, BLOBHASH STRING);";
    public const string CREATE_CLUBS_TABLE = "CREATE TABLE IF NOT EXISTS CLUBS_TABLE (CLUBIDBIGINT PRIMARY KEY, CLUBBLOB BYTEA, CLUBHASH STRING);";



}