namespace Meepl.Util;

/// <summary>
/// This will contain the updated SQL schema for all of Meepl
/// </summary>
public class SQLCommands
{
    public static readonly string CREATE_TABLEBOUND_PROFILE_TABLE = "CREATE TABLE IF NOT EXISTS TABLEBOUND_PROFILE(TABLEBOUND_ID BIGINT PRIMARY KEY, USERNAME VARCHAR(16), BIO VARCHAR(200), ACTION VARCHAR(32), ICONCDNLINK VARCHAR(128), TITLE BIGINT, STATUS SMALLINT);";

    #region Platform Profiles
    public static readonly string CREATE_PLATFORM_PROFILE_TABLE_META = "CREATE TABLE IF NOT EXISTS META_PROFILE(TABLEBOUND_ID BIGINT, META_ID BIGINT, CONSTRAINT FK_TID FOREIGN KEY (TABLEBOUND_ID) REFERENCES TABLEBOUND_PROFILE (TABLEBOUND_ID));";
    public static readonly string CREATE_PLATFORM_PROFILE_TABLE_STEAM = "CREATE TABLE IF NOT EXISTS STEAM_PROFILE(TABLEBOUND_ID BIGINT, STEAM_ID BIGINT, CONSTRAINT FK_TID FOREIGN KEY (TABLEBOUND_ID) REFERENCES TABLEBOUND_PROFILE (TABLEBOUND_ID));";
    public static readonly string CREATE_PLATFORM_PROFILE_TABLE_APPLE = "CREATE TABLE IF NOT EXISTS APPLE_PROFILE(TABLEBOUND_ID BIGINT, APPLE_ID BIGINT, CONSTRAINT FK_TID FOREIGN KEY (TABLEBOUND_ID) REFERENCES TABLEBOUND_PROFILE (TABLEBOUND_ID));";
    public static readonly string CREATE_PLATFORM_PROFILE_TABLE_DISCORD = "CREATE TABLE IF NOT EXISTS DISCORD_PROFILE(TABLEBOUND_ID BIGINT, DISCORD_ID BIGINT, CONSTRAINT FK_TID FOREIGN KEY (TABLEBOUND_ID) REFERENCES TABLEBOUND_PROFILE (TABLEBOUND_ID));";
    public static readonly string CREATE_PLATFORM_PROFILE_TABLE_EPIC = "CREATE TABLE IF NOT EXISTS EPIC_PROFILE(TABLEBOUND_ID BIGINT, EPIC_ID BIGINT, CONSTRAINT FK_TID FOREIGN KEY (TABLEBOUND_ID) REFERENCES TABLEBOUND_PROFILE (TABLEBOUND_ID));";
    #endregion
    
    
}